### PR TITLE
Feature/disclaimer text

### PR DESCRIPTION
**Pull request by csubhodeep**
* closes #42 #43 
* Fix showing "No rides found" message even when nothing has been searched for in the ride search page
* Label warning getting printed in stdout in the back -> potentially makes things slower
* Adjust font size of forms so that they are smaller than page title.
* Add an extra field to the table - `insert_timestamp_utc`

### CODE REVIEW

**Comment by nikhilchh** [comment]
Any route specific details you would like to share ? 

what is the meaning of this question ?

**Comment by csubhodeep** [comment]
> Any route specific details you would like to share ?
> 
> what is the meaning of this question ?

It is vague, you have edit access to the form, feel free to modify the questions

**Comment by nikhilchh** [comment]
It allowed me to post 11 digit phone number. 

image

**Review by nikhilchh — APPROVED** [review]
1- Google form could just have 1 field called "feedback" to keep it simple.
2- Only allow 10 digit phone number.

**Comment by nikhilchh** [comment]
> > Any route specific details you would like to share ?
> > what is the meaning of this question ?
> 
> It is vague, you have edit access to the form, feel free to modify the questions

How about this ?
Is the city you're looking for not listed in the dropdown? Please specify the city name below.

**Pull request merged**
